# Generated by Django 5.2.6 on 2025-09-23 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qr_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verification_method',
            field=models.CharField(choices=[('QR', 'QR Code'), ('FACE', 'Face Recognition')], default='QR', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
