# Generated by Django 5.2.6 on 2025-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_student_created_at_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
